services:
  - type: web
    name: AfyaLink-backend
    env: node
    repo: your/repo
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
  - type: web
    name: AfyaLink-frontend
    env: static
    repo: your/repo
    buildCommand: cd frontend && npm install && npm run build
    startCommand: rm -f /tmp/placeholder
